# Secret Scanning Configuration
# This file configures secret scanning patterns for GitHub Advanced Security

name: "Secret Scanning Patterns"

patterns:
  # AWS Access Key ID
  - name: "AWS Access Key ID"
    regex: "(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}"
    description: "AWS Access Key ID"
    
  # AWS Secret Access Key  
  - name: "AWS Secret Access Key"
    regex: "[A-Za-z0-9/+=]{40}"
    description: "AWS Secret Access Key"
    
  # GitHub Personal Access Token
  - name: "GitHub Personal Access Token"
    regex: "ghp_[a-zA-Z0-9]{36}"
    description: "GitHub Personal Access Token"
    
  # GitHub OAuth App Token
  - name: "GitHub OAuth App Token"
    regex: "gho_[a-zA-Z0-9]{36}"
    description: "GitHub OAuth App Token"
    
  # GitHub App Token
  - name: "GitHub App Token"
    regex: "ghu_[a-zA-Z0-9]{36}"
    description: "GitHub App Token"
    
  # GitHub Refresh Token
  - name: "GitHub Refresh Token"
    regex: "ghr_[a-zA-Z0-9]{76}"
    description: "GitHub Refresh Token"
    
  # GitHub Fine-grained Token
  - name: "GitHub Fine-grained Token"
    regex: "ghs_[a-zA-Z0-9]{36}"
    description: "GitHub Fine-grained Token"
    
  # Generic API Keys
  - name: "Generic API Key"
    regex: "(?i)(api[_-]?key|apikey|api[_-]?secret|secret)[\"'`]*[\\s]*[:=][\\s]*[\"'`]*[a-zA-Z0-9_\\-]{16,}[\"'`]*"
    description: "Generic API Key pattern"
    
  # Private Keys
  - name: "Private Key"
    regex: "-----BEGIN (RSA |OPENSSH |DSA |EC |PGP )?PRIVATE KEY-----"
    description: "Private key header"
    
  # Database URLs
  - name: "Database URL"
    regex: "(?i)(mysql|postgres|mongodb|redis):\\/\\/[^:]+:[^@]+@[^\\/]+"
    description: "Database connection string"
    
  # JWT Tokens
  - name: "JWT Token"
    regex: "eyJ[a-zA-Z0-9_-]*\\.eyJ[a-zA-Z0-9_-]*\\.[a-zA-Z0-9_-]*"
    description: "JSON Web Token"
    
  # Slack Tokens
  - name: "Slack Token"
    regex: "xox[baprs]-[a-zA-Z0-9-]+"
    description: "Slack bot/user/app token"
    
  # Stripe API Keys
  - name: "Stripe API Key"
    regex: "(sk|pk)_(live|test)_[a-zA-Z0-9]{24}"
    description: "Stripe API key"
